name: CI

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build'
        required: true
        default: '0.0.0'

    
jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: '.\src\Maui.Plugins.PageResolver.sln'

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
  

    # - name: Install workloads
    #   run: dotnet workload install maui maui-windows

    # - name: Restore dependencies
    #   run: dotnet restore $env:SOLUTION

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.x.x
        include-prerelease: false

    - name: Install workloads
      run: dotnet workload install maui

    - name: Build
      run: dotnet build $env:SOLUTION --configuration $env:BUILD_CONFIG -p:Version=${{ github.event.inputs.version }}

    # - name: Run tests
    #   run: dotnet test /p:Configuration=$env:BUILD_CONFIG --no-restore --no-build --verbosity normal

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Publish
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}